### ISSUE TITLE
NameError: name '_cast_uint32_native' is not defined

### ISSUE THREAD

**Issue by konyshev-dmitry** [Bluetooth-Devices/dbus-fast#129]
Using Bleak to fetch Bluetooth Low Energy (BLE) devices.

Versions of dbus-fast <=1.50.0 are working fine.
Versions of dbus-fast >=1.51.0 give:
`File "/home/d/.local/lib/python3.11/site-packages/dbus_fast/_private/unmarshaller.py", line 434, in _read_header
    self._body_len = _cast_uint32_native(self._buf, 4)  # pragma: no cover
                     ^^^^^^^^^^^^^^^^^^^
NameError: name '_cast_uint32_native' is not defined `

Ubuntu 20.04.5 (amd64 and aarch64), Python 3.8-3.11

**Comment by bdraco** [comment]
We don’t have python 3.11 support yet, but your post implies you have the issue on other versions as well.

Can you post the trace from 3.10/3.9/3.8?

**Comment by bdraco** [comment]
Are you using the wheels from PyPI or building for source?

Is the cython extension being compiled or are you running pure python only?

**Comment by bdraco** [comment]
Pushed 1.59.2

Please let me know if that resolves it for you

**Comment by bdraco** [comment]
It will take 10-15 minutes before wheels are uploaded
https://github.com/Bluetooth-Devices/dbus-fast/actions/runs/3360664409

**Comment by bdraco** [comment]
1.61.0 has python 3.11 support
