### ISSUE TITLE
Allow passing hardcoded uid to AuthExternal

### ISSUE THREAD

**Issue by kiwiz** [Bluetooth-Devices/dbus-fast#188]
**Is your feature request related to a problem? Please describe.**

I'm trying to connect to the system DBus within a Docker container that is utilizing a user namespace. This fails, as the `os.uid()` call [here](https://github.com/Bluetooth-Devices/dbus-fast/blob/main/src/dbus_fast/auth.py#L69) returns the remapped UID (which is entirely expected).

**Describe the solution you'd like**

For my use case, I would like to pass a hardcoded UID to `AuthExternal`, perhaps via the constructor or an env variable. If this sounds like a reasonable change, I can submit a PR.

**Additional context**

I arrived here via the following path:

* [home-assistant:bluetooth](https://github.com/home-assistant/core/blob/dev/homeassistant/components/bluetooth)
* [bleak](https://github.com/hbldh/bleak)
* dbus-fast

Let me know if this feature request would be better suited for one of those repos.

**Comment by bdraco** [comment]
We can accept a PR for this via the constructor as an optional keyword arg as long as it has test coverage 👍
