### ISSUE TITLE
Introspection returns bogus child paths

### ISSUE THREAD

**Issue by mriemensberger** [Bluetooth-Devices/dbus-fast#279]
**Describe the bug**

I see the following path hierarchy when showing the object tree with busctl tree `com.example.Service`
```
└─/com
  └─/com/example
    └─/com/example/service
      ├─/com/example/service/item
      │ ├─/com/example/service/item/0
      │ ├─/com/example/service/item/1
      │ │ ├─/com/example/service/item/1/0
      │ │ └─/com/example/service/item/1/1
      │ ├─/com/example/service/item/10
      │ ├─/com/example/service/item/11
      │ └─/com/example/service/item/2
...
```

I would expect to see only
```
└─/com
  └─/com/example
    └─/com/example/service
      ├─/com/example/service/item
      │ ├─/com/example/service/item/0
      │ ├─/com/example/service/item/1
      │ ├─/com/example/service/item/10
      │ ├─/com/example/service/item/11
      │ └─/com/example/service/item/2
...
```

The `/com/example/service/item/1/0` and `/com/example/service/item/1/1` are bogus and have never been exported by the service. They also show up without any interfaces when being introspected with busctl introspect.

It looks like that the computation of the children nodes in https://github.com/Bluetooth-Devices/dbus-fast/blob/f0fc6668b9543bd81e2438fe78a54c31702a4bc5/src/dbus_fast/message_bus.py#L650 is wrong if some paths are prefixes for other paths.  For example, `/com/example/service/item/1` is a prefix of `/com/example/service/item/10`, but the latter is not a child of the former.

**To Reproduce**

* Expose object paths where one path is a prefix of another path but they have no parent-child relationship. 
* Introspect with busctl tree

**Additional context**

Suggested fix: Replace https://github.com/Bluetooth-Devices/dbus-fast/blob/f0fc6668b9543bd81e2438fe78a54c31702a4bc5/src/dbus_fast/message_bus.py#L663 with

```py
            if not export_path.startswith(path + '/'):
```

**Comment by bdraco** [comment]
That looks like a reasonable fix. It might need an equality check as well for the exact path (but not sure on that one without a test)

**Comment by mriemensberger** [comment]
I ended up with this fix:
```
--- a/src/dbus_fast/message_bus.py	2024-05-01 00:20:01.242137424 +0000
+++ b/src/dbus_fast/message_bus.py	2024-05-01 00:20:17.490082951 +0000
@@ -665,6 +665,9 @@
 
             child_path = export_path.split(path, maxsplit=1)[1]
+            if path and path[-1] != "/" and child_path and child_path[0] != "/":
+                continue
+
             child_path = child_path.lstrip("/")
             child_name = child_path.split("/", maxsplit=1)[0]
 
             children.add(child_name)

```

**Comment by mriemensberger** [comment]
Otherwise the root path introspection (path = "/" doesn't work).

**Comment by mriemensberger** [comment]
But there is probably a prettier way to fix it.

**Comment by bdraco** [comment]
If you open a PR with a test, I can do a proper review this weekend assuming the Home Assistant release tomorrow doesn't eat up all my available time

**Comment by mriemensberger** [comment]
PR #280 created. Please review.

**Comment by mriemensberger** [comment]
@bdraco Thanks for handing this so quickly.

**Comment by bdraco** [comment]
Thank you for your contributions!
